## This notebook is for the "d2d" project

#### Here we will analyze the image to exract data from it

##### Here we will use mainly python-tesserect and opencv to do this

In [2]:
#import all the things
import cv2
import pytesseract
import numpy as np

In [3]:
#Read an Image
img = cv2.imread('Images/2.jpeg')
print(img)

[[[226 223 219]
  [226 223 219]
  [226 223 219]
  ...
  [113 115 123]
  [112 114 122]
  [110 113 121]]

 [[226 223 219]
  [226 223 219]
  [226 223 219]
  ...
  [116 118 126]
  [114 116 124]
  [112 115 123]]

 [[226 223 219]
  [226 223 219]
  [226 223 219]
  ...
  [118 120 128]
  [117 119 127]
  [114 117 125]]

 ...

 [[227 226 222]
  [227 226 222]
  [227 226 222]
  ...
  [ 19  30  50]
  [ 19  33  52]
  [ 16  30  53]]

 [[227 226 222]
  [227 226 222]
  [227 226 222]
  ...
  [ 20  31  51]
  [ 19  33  52]
  [ 17  31  54]]

 [[227 226 222]
  [227 226 222]
  [227 226 222]
  ...
  [ 20  31  51]
  [ 20  34  53]
  [ 17  31  54]]]


##### as above we can see the output of the image in array

In [4]:
#Now lets try with tesseract

text = pytesseract.image_to_string('Images/2.jpeg')
print(text)

‘ q

“s
@ DUTCH BANGLA BANK

Transaction Sum pee enterprise
Customer Co
woes con 1094643

 

Transaction Type: Fund Transfer po- 12731
Transaction ID : 102674119

Date : December 02, 2021
Initiator : 01711486765

From Account : 7017512561124
Account Name : MD.FAZLERABBI

To Account : 1031100022462
Account Name : RICECO INTERNATIONAL
Amount : 27076.0

Fee 254.15

Generated Time = 2021/12/02 14:40:55

Teller Signature Customer Signature

This is a system generated report of DBBL



##### So, we can see we get the output data as text from the image. To get better output we need to do some preprocessing

In [5]:
#convert to grayscale
img = cv2.imread('Images/2.jpeg', 0)

#Threshold
img = cv2.threshold(img, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)[1]

#Remove noise
img = cv2.medianBlur(img, 5)

##### Now after prepocessing we will do the same as above

In [6]:
text = pytesseract.image_to_string('Images/2.jpeg')
print(text)

‘ q

“s
@ DUTCH BANGLA BANK

Transaction Sum pee enterprise
Customer Co
woes con 1094643

 

Transaction Type: Fund Transfer po- 12731
Transaction ID : 102674119

Date : December 02, 2021
Initiator : 01711486765

From Account : 7017512561124
Account Name : MD.FAZLERABBI

To Account : 1031100022462
Account Name : RICECO INTERNATIONAL
Amount : 27076.0

Fee 254.15

Generated Time = 2021/12/02 14:40:55

Teller Signature Customer Signature

This is a system generated report of DBBL



In [7]:
# Now lets split the text
test = text.split("\n")
print(test)

['‘ q', '', '“s', '@ DUTCH BANGLA BANK', '', 'Transaction Sum pee enterprise', 'Customer Co', 'woes con 1094643', '', ' ', '', 'Transaction Type: Fund Transfer po- 12731', 'Transaction ID : 102674119', '', 'Date : December 02, 2021', 'Initiator : 01711486765', '', 'From Account : 7017512561124', 'Account Name : MD.FAZLERABBI', '', 'To Account : 1031100022462', 'Account Name : RICECO INTERNATIONAL', 'Amount : 27076.0', '', 'Fee 254.15', '', 'Generated Time = 2021/12/02 14:40:55', '', 'Teller Signature Customer Signature', '', 'This is a system generated report of DBBL', '\x0c']


In [8]:
type(test)

list

In [9]:
with open('readme.txt', 'w') as f:
    for line in test:
        f.write(line)
        f.write('\n')

### Now we need to save the info in excel

In [6]:
import csv
with open('wordstest.csv', 'w', encoding='UTF8') as f:
    writer = csv.writer(f)

    # write the header
    writer.writerow(text)
