## This notebook is for the "d2d" project

#### Here we will analyze the image to exract data from it

##### Here we will use mainly python-tesserect and opencv to do this

In [5]:
#import all the things
import cv2
import pytesseract
import numpy as np

In [6]:
#Read an Image
img = cv2.imread('Images/1.jpeg')
print(img)

[[[ 52  92 121]
  [ 58  98 127]
  [ 61 101 130]
  ...
  [129 147 178]
  [127 145 176]
  [125 143 174]]

 [[ 63 103 132]
  [ 65 105 133]
  [ 65 105 134]
  ...
  [127 145 176]
  [126 144 175]
  [125 143 174]]

 [[ 73 113 141]
  [ 72 113 138]
  [ 68 108 136]
  ...
  [125 143 174]
  [125 143 174]
  [125 143 174]]

 ...

 [[ 10   9  11]
  [ 10   9  11]
  [ 10   9  11]
  ...
  [147 164 167]
  [147 164 167]
  [147 164 167]]

 [[ 10   9  11]
  [ 10   9  11]
  [ 10   9  11]
  ...
  [147 164 167]
  [147 164 167]
  [147 164 167]]

 [[ 10   9  11]
  [ 10   9  11]
  [ 10   9  11]
  ...
  [147 164 167]
  [147 164 167]
  [147 164 167]]]


##### as above we can see the output of the image in array

In [7]:
#Now lets try with tesseract

text = pytesseract.image_to_string('Images/1.jpeg')
print(text)

JUTCH-BANGLA BANK LIMITED
A\CADEMY MR FT=2 CHUA
DATE IME TERMINAL 1D
12/12/21 09:34:01 25134094 P
M/S Amin |5
CARD NO # xxxxxxxxxxxxxxx‘;n,rla
09SFY|

TXN NO. 00325472 RESP CODE: O

FUNDS TRANSFER

FR A/C#: 1351010120022

TO A/C#: 1031100022462

TXN AMOUNT: TK 52.00 52_7;-"

AVAIL BAL : TK. AT

@W’L{ /3'4

EMV APP ID: F0504442420110
THANK YOU FOR USING
DBBL NETWORK




##### So, we can see we get the output data as text from the image. To get better output we need to do some preprocessing

In [8]:
#convert to grayscale
img = cv2.imread('Images/1.jpeg', 0)

#Threshold
img = cv2.threshold(img, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)[1]

#Remove noise
img = cv2.medianBlur(img, 5)

##### Now after prepocessing we will do the same as above

In [9]:
text = pytesseract.image_to_string('Images/1.jpeg')
print(text)

JUTCH-BANGLA BANK LIMITED
A\CADEMY MR FT=2 CHUA
DATE IME TERMINAL 1D
12/12/21 09:34:01 25134094 P
M/S Amin |5
CARD NO # xxxxxxxxxxxxxxx‘;n,rla
09SFY|

TXN NO. 00325472 RESP CODE: O

FUNDS TRANSFER

FR A/C#: 1351010120022

TO A/C#: 1031100022462

TXN AMOUNT: TK 52.00 52_7;-"

AVAIL BAL : TK. AT

@W’L{ /3'4

EMV APP ID: F0504442420110
THANK YOU FOR USING
DBBL NETWORK




In [10]:
# Now lets split the text
test = text.split("\n")
print(test)

['JUTCH-BANGLA BANK LIMITED', 'A\\CADEMY MR FT=2 CHUA', 'DATE IME TERMINAL 1D', '12/12/21 09:34:01 25134094 P', 'M/S Amin |5', 'CARD NO # xxxxxxxxxxxxxxx‘;n,rla', '09SFY|', '', 'TXN NO. 00325472 RESP CODE: O', '', 'FUNDS TRANSFER', '', 'FR A/C#: 1351010120022', '', 'TO A/C#: 1031100022462', '', 'TXN AMOUNT: TK 52.00 52_7;-"', '', 'AVAIL BAL : TK. AT', '', "@W’L{ /3'4", '', 'EMV APP ID: F0504442420110', 'THANK YOU FOR USING', 'DBBL NETWORK', '', '']


In [11]:
type(test)

list

In [12]:
with open('details.txt', 'w') as f:
    for line in test:
        f.write(line)
        f.write('\n')

### Now we need to save the info in csv

In [13]:
import csv
with open('wordstest.csv', 'w', encoding='UTF8') as f:
    writer = csv.writer(f)

    # write the header
    writer.writerow(text)


### Now we need to build a excel sheet

In [14]:
# import xlsxwriter module
import xlsxwriter

workbook = xlsxwriter.Workbook('Example2.xlsx')
worksheet = workbook.add_worksheet()

# Start from the first cell.
# Rows and columns are zero indexed.
row = 0
column = 0
# iterating through content list
for item in test :

	# write operation perform
	worksheet.write(column, row, item)

	# incrementing the value of row by one
	# with each iterations.
	row += 1
	
workbook.close()
